### ISSUE TITLE
Python error during usage

### ISSUE THREAD

**Issue by wikijm** [dhondta/AppmemDumper#1]
Hi @dhondta 

I encounter issue below when using 04/29/2019 release with `app-mem-dumper -v dump.dmp`:

```python
Traceback (most recent call last):
  File "/usr/local/bin/app-mem-dumper", line 4, in <module>
    __import__('pkg_resources').run_script('appmemdumper==2.3.2', 'app-mem-dumper')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/app-mem-dumper' not found in metadata at '/usr/local/lib/python2.7/dist-packages/appmemdumper-2.3.2.dist-info'
```

I'm using volatility 2.6.1 on Linux kali 5.3.0-kali2-amd64.
Every requirement are installed.

Sincerely,
WikiJM

**Comment by dhondta** [comment]
Please try reinstalling the package using `pip install --reinstall appmemdumper` and tell me if you still face the issue.

**Comment by wikijm** [comment]
I forgot to say that I'm using those commands to install:
```bash
cd /tmp/
git clone https://github.com/dhondta/AppmemDumper
cd ./AppmemDumper/
pip install -r requirements.txt
chmod 755 setup.py
./setup.py install
```

Because `pip install appmemdumper` give me this:
```bash
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement appmemdump (from versions: none)
ERROR: No matching distribution found for appmemdump
```

I assume that you ask me to use `pip install appmemdumper --upgrade --force-reinstall`.

Here is the result:
```bash
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /root/.cache/pip/wheels/d5/6d/cd/7b3bd8c867c58dcd5f99350963bf036f743bd2a0b19d50888c/appmemdumper-2.3.2-cp27-none-any.whl
ERROR: Could not find a version that satisfies the requirement volatility (from appmemdumper) (from versions: none)
ERROR: No matching distribution found for volatility (from appmemdumper)
```

**Comment by dhondta** [comment]
OK, you're completely right, I screwed up with command's syntax...

I updated a few things in the project, namely I removed `volatility` from `requirements.txt` as it should be installed apart. So, please install Volatility according to the `README.md` first, then `pip install appmemdumper --upgrade --force-reinstall` and tell me if it fixed the issue.

**Comment by wikijm** [comment]
It's seems to work after two --force-reinstall.
Thank you so much 😃
